### ISSUE TITLE
Create a Quick Start Tutorial

### ISSUE THREAD

**Issue by slavad** [bennn/mechanics#30]
@bennn it would be nice if you create a quick start guide for this package.
I think that some users of your package are new to the lisp world and the racket world in particular, so it might be difficult for them to start using this package.

E.g. here is what I do:
```
#lang mechanics
(require mechanics)

((D cube) 5)
```
And here is the error I get
```
Error: struct:exn:fail:syntax:unbound

code.rkt:4:2: D: unbound identifier
  in: D
```

I have a strong feeling that I'm missing a very simple thing (at least for an experienced Lips user), but what exactly am I missing?

**Comment by bennn** [comment]
Yes, this package definitely needs a quick start guide & docs.

But first it needs an implementation! This package is not at all ready for users; it's missing maybe 98% of the `scmutils` functionality.

The error you're seeing in because `D` is not provided. It doesn't exist yet in `#lang mechanics`.

- - -

If you're looking for code to go with the SICM book, Alex Gian's [`rat`](https://github.com/alexgian/rat) code is in better shape, but also a work in progress.

If you're looking for math library functions, though, then [`racket/math`](https://docs.racket-lang.org/reference/generic-numbers.html), [`math`](https://docs.racket-lang.org/math/index.html), and [`plot`](https://docs.racket-lang.org/plot/utils.html) should help.

**Comment by slavad** [comment]
thx for the info.
